repos:
  - repo: https://github.com/pycqa/flake8.git
    rev: 5.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-docstrings==1.5.0'
        ]
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        args: ["--no-markdown-linebreak-ext"]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "0", "--wrap-summaries", "0"]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.1
    hooks:
    - id: mdformat
      additional_dependencies: [
        'mdformat-tables==0.4.0'
      ]
